/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas_Tienda;

/**
 *
 * @author PC
 */
public class C_Productos_Nuevo_Producto extends javax.swing.JPanel {

    /**
     * Creates new form C_Productos_Nuevo_Producto
     */
    public C_Productos_Nuevo_Producto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTipoPrenda = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        panel3 = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(3, 0, 1, 0));

        panel1.setBackground(new java.awt.Color(255, 252, 250));

        jLabel8.setBackground(new java.awt.Color(255, 252, 250));
        jLabel8.setFont(new java.awt.Font("Georgia", 1, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(58, 42, 38));
        jLabel8.setText("AGREGAR NUEVO PRODUCTO");
        jLabel8.setAlignmentX(32.0F);
        jLabel8.setAlignmentY(22.0F);
        jLabel8.setMaximumSize(new java.awt.Dimension(180, 28));
        jLabel8.setMinimumSize(new java.awt.Dimension(180, 28));
        jLabel8.setPreferredSize(new java.awt.Dimension(32, 22));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
        );

        add(panel1);

        panel2.setBackground(new java.awt.Color(255, 252, 250));
        panel2.setLayout(new java.awt.GridLayout(6, 2, 2, 0));

        jLabel2.setBackground(new java.awt.Color(255, 252, 250));
        jLabel2.setForeground(new java.awt.Color(184, 123, 103));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID");
        panel2.add(jLabel2);

        txtIdProducto.setForeground(new java.awt.Color(169, 154, 148));
        txtIdProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel2.add(txtIdProducto);

        jLabel3.setBackground(new java.awt.Color(255, 252, 250));
        jLabel3.setForeground(new java.awt.Color(184, 123, 103));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PRODUCTO");
        panel2.add(jLabel3);

        txtProducto.setForeground(new java.awt.Color(169, 154, 148));
        txtProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel2.add(txtProducto);

        jLabel4.setBackground(new java.awt.Color(255, 252, 250));
        jLabel4.setForeground(new java.awt.Color(184, 123, 103));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TIPO PRENDA");
        panel2.add(jLabel4);

        txtTipoPrenda.setForeground(new java.awt.Color(169, 154, 148));
        txtTipoPrenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel2.add(txtTipoPrenda);

        jLabel5.setBackground(new java.awt.Color(255, 252, 250));
        jLabel5.setForeground(new java.awt.Color(184, 123, 103));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DESCRIPCION");
        panel2.add(jLabel5);

        txtDescripcion.setForeground(new java.awt.Color(169, 154, 148));
        txtDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel2.add(txtDescripcion);

        jLabel6.setBackground(new java.awt.Color(255, 252, 250));
        jLabel6.setForeground(new java.awt.Color(184, 123, 103));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PRECIO");
        panel2.add(jLabel6);

        txtPrecio.setForeground(new java.awt.Color(169, 154, 148));
        txtPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel2.add(txtPrecio);

        jLabel7.setBackground(new java.awt.Color(255, 252, 250));
        jLabel7.setForeground(new java.awt.Color(184, 123, 103));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("STOCK");
        panel2.add(jLabel7);

        txtStock.setForeground(new java.awt.Color(169, 154, 148));
        txtStock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel2.add(txtStock);

        add(panel2);

        panel3.setBackground(new java.awt.Color(255, 252, 250));

        btnAtras.setBackground(new java.awt.Color(255, 243, 238));
        btnAtras.setForeground(new java.awt.Color(184, 123, 103));
        btnAtras.setText("ATRAS");
        btnAtras.addActionListener(this::btnAtrasActionPerformed);

        btnConfirmar.setBackground(new java.awt.Color(255, 243, 238));
        btnConfirmar.setForeground(new java.awt.Color(184, 123, 103));
        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 366, Short.MAX_VALUE)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        add(panel3);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
       A_Dashboard dashboard =
            (A_Dashboard)
            javax.swing.SwingUtilities
                    .getWindowAncestor(this);

    if (dashboard != null) {

        dashboard.mostrarPanel(
                new C_Productos()
        );
    }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
     // 1. Validar que los campos principales no estén vacíos
    if (txtProducto.getText().trim().isEmpty() || 
        txtTipoPrenda.getText().trim().isEmpty() || 
        txtPrecio.getText().trim().isEmpty() || 
        txtStock.getText().trim().isEmpty()) {
        
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Por favor, complete todos los campos (Producto, Tipo, Precio y Stock).", 
            "Campos incompletos", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        // 2. Recolectar datos de los campos de texto
        String producto = txtProducto.getText().trim();
        String tipoPrenda = txtTipoPrenda.getText().trim();
        String descripcion = txtDescripcion.getText().trim();
        
        // Unificar Producto y Descripción para que encaje en la columna de tu BD
        String descFinal = producto + " - " + descripcion; 
        
        // Convertir textos a números
        double precio = Double.parseDouble(txtPrecio.getText().trim());
        int stock = Integer.parseInt(txtStock.getText().trim());

        // 3. Conectar a BD y preparar la consulta INSERT
        // Omitimos id_producto (es autoincrementable) e id_proveedor (queda NULL por ahora)
        java.sql.Connection con = conexionLiv.conectar();
        String sql = "INSERT INTO producto (tipo_prenda, descripcion, precio, stock_inventario) VALUES (?, ?, ?, ?)";
        
        java.sql.PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, tipoPrenda);
        ps.setString(2, descFinal);
        ps.setDouble(3, precio);
        ps.setInt(4, stock);
        
        // 4. Ejecutar la inserción
        int resultado = ps.executeUpdate();
        
        if (resultado > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Producto agregado exitosamente.");
            A_Dashboard dashboard =
        (A_Dashboard)
        javax.swing.SwingUtilities
                .getWindowAncestor(this);

if (dashboard != null) {

    dashboard.mostrarPanel(
            new C_Productos()
    );
}
            
            // 5. Limpiar las cajas de texto para un nuevo ingreso
            txtProducto.setText("");
            txtTipoPrenda.setText("");
            txtDescripcion.setText("");
            txtPrecio.setText("");
            txtStock.setText("");
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "No se pudo agregar el producto.", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
        ps.close();
        con.close();
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "El precio y el stock deben ser valores numéricos válidos (Ej. Precio: 45.50).", 
            "Error de formato", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error al guardar en la base de datos: " + e.getMessage(), 
            "Error BD", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTipoPrenda;
    // End of variables declaration//GEN-END:variables
}
