package Vistas_Tienda;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author PC
 */
public class E_Ventas extends javax.swing.JPanel {

    /**
     * Creates new form B_Resumen
     */
    public E_Ventas() {
        if (cboHistorial.getItemCount() == 0) {
        cboHistorial.addItem("Todos los registros");
        cboHistorial.addItem("Ventas de hoy");
        cboHistorial.addItem("Esta semana");
        cboHistorial.addItem("Este mes");
    }
    
    // Cargar el historial al iniciar
    cargarHistorialVentas();
    }
public void cargarHistorialVentas() {
    DefaultTableModel modelo = (DefaultTableModel) tableHistorialVentas.getModel();
    modelo.setRowCount(0); // Limpiar tabla

    String sql = "SELECT v.id_venta, v.id_cliente, SUM(d.cantidad) AS n_productos, v.fecha, v.hora, v.total " +
                 "FROM venta v " +
                 "LEFT JOIN detalle_venta d ON v.id_venta = d.id_venta " +
                 "GROUP BY v.id_venta, v.id_cliente, v.fecha, v.hora, v.total " +
                 "ORDER BY v.fecha DESC, v.hora DESC";

    try {
        Connection con = (Connection) conexionLiv.conectar();
        PreparedStatement ps = (PreparedStatement) con.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Object[] fila = {
                rs.getInt("id_venta"),
                rs.getInt("id_cliente"),
                rs.getInt("n_productos"),
                rs.getDate("fecha"),
                rs.getTime("hora"),
                String.format("S/ %.2f", rs.getDouble("total"))
            };
            modelo.addRow(fila);
        }

        rs.close();
        ps.close();
        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar historial de ventas: " + e.getMessage());
    }
}
public void cargarProductosVendidos(int idVenta) {
    DefaultTableModel modelo = (DefaultTableModel) tableProductosVendidos.getModel();
    modelo.setRowCount(0); // Limpiar tabla inferior

    String sql = "SELECT p.id_producto, p.tipo_prenda, p.descripcion, d.cantidad, d.precio_unitario, d.subtotal " +
                 "FROM detalle_venta d " +
                 "INNER JOIN producto p ON d.id_producto = p.id_producto " +
                 "WHERE d.id_venta = ?";

    try {
        Connection con = (Connection) conexionLiv.conectar();
        PreparedStatement ps = (PreparedStatement) con.prepareStatement(sql);
        ps.setInt(1, idVenta);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Object[] fila = {
                rs.getInt("id_producto"),
                rs.getString("tipo_prenda"), // PRODUCTO
                rs.getString("tipo_prenda"), // TIPO
                rs.getString("descripcion"), // DESCRIPCION
                rs.getInt("cantidad"),       // CANTIDAD VENDIDA
                String.format("S/ %.2f", rs.getDouble("precio_unitario")), // PRECIO
                String.format("S/ %.2f", rs.getDouble("subtotal"))         // RECAUDO
            };
            modelo.addRow(fila);
        }

        rs.close();
        ps.close();
        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar detalles de la venta: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIngresosVentas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboHistorial = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHistorialVentas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProductosVendidos = new javax.swing.JTable();
        btnVerDetallesVenta = new javax.swing.JButton();
        btnActualizarIngresos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setText("REPORTES");

        cboHistorial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CBO HISTORIAL", "DIA", "MES", "AÑO" }));

        tableHistorialVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID_VENTA", "ID_CLIENTE", "N PRODUCTOS", "FECHA", "HORA", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(tableHistorialVentas);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HISTORIAL DE VENTAS");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HISTORIAL DE VENTAS");

        tableProductosVendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "PRODUCTO", "TIPO", "DESCRIPCION", "CANTIDAD VENDIDA", "PRECIO", "RECAUDO"
            }
        ));
        jScrollPane2.setViewportView(tableProductosVendidos);

        btnVerDetallesVenta.setText("VER DETALLES");
        btnVerDetallesVenta.addActionListener(this::btnVerDetallesVentaActionPerformed);

        btnActualizarIngresos.setText("INGRESOS");
        btnActualizarIngresos.addActionListener(this::btnActualizarIngresosActionPerformed);

        javax.swing.GroupLayout txtIngresosVentasLayout = new javax.swing.GroupLayout(txtIngresosVentas);
        txtIngresosVentas.setLayout(txtIngresosVentasLayout);
        txtIngresosVentasLayout.setHorizontalGroup(
            txtIngresosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtIngresosVentasLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(txtIngresosVentasLayout.createSequentialGroup()
                .addGroup(txtIngresosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtIngresosVentasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(txtIngresosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)))
                    .addGroup(txtIngresosVentasLayout.createSequentialGroup()
                        .addGroup(txtIngresosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txtIngresosVentasLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnVerDetallesVenta))
                            .addGroup(txtIngresosVentasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cboHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnActualizarIngresos)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        txtIngresosVentasLayout.setVerticalGroup(
            txtIngresosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtIngresosVentasLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txtIngresosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarIngresos)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnVerDetallesVenta)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIngresosVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtIngresosVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerDetallesVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetallesVentaActionPerformed
// 1. Verificamos si el usuario seleccionó una fila en la tabla superior
    int filaSeleccionada = tableHistorialVentas.getSelectedRow();
    
    if (filaSeleccionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Por favor, seleccione una venta del historial superior para ver sus detalles.", 
            "Aviso", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // 2. Extraemos el ID_VENTA de la primera columna (columna 0)
    int idVenta = Integer.parseInt(tableHistorialVentas.getValueAt(filaSeleccionada, 0).toString());
    
    // 3. Consultamos la base de datos para llenar la tabla inferior
    javax.swing.table.DefaultTableModel modeloDetalle = (javax.swing.table.DefaultTableModel) tableProductosVendidos.getModel();
    modeloDetalle.setRowCount(0); // Limpiamos la tabla de abajo

    String sql = "SELECT p.id_producto, p.tipo_prenda, p.descripcion, d.cantidad, d.precio_unitario, d.subtotal " +
                 "FROM detalle_venta d " +
                 "INNER JOIN producto p ON d.id_producto = p.id_producto " +
                 "WHERE d.id_venta = ?";

    try {
        java.sql.Connection con = conexionLiv.conectar();
        java.sql.PreparedStatement ps = con.prepareStatement(sql);
        ps.setInt(1, idVenta);
        java.sql.ResultSet rs = ps.executeQuery();

        boolean hayProductos = false;
        while (rs.next()) {
            hayProductos = true;
            Object[] fila = {
                rs.getInt("id_producto"),
                rs.getString("tipo_prenda"), // PRODUCTO
                rs.getString("tipo_prenda"), // TIPO
                rs.getString("descripcion"), // DESCRIPCION
                rs.getInt("cantidad"),       // CANTIDAD VENDIDA
                String.format("S/ %.2f", rs.getDouble("precio_unitario")), // PRECIO
                String.format("S/ %.2f", rs.getDouble("subtotal"))         // RECAUDO
            };
            modeloDetalle.addRow(fila);
        }

        if (!hayProductos) {
            javax.swing.JOptionPane.showMessageDialog(this, "Esta venta no registra productos asociados.", "Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

        rs.close();
        ps.close();
        con.close();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar los detalles: " + e.getMessage(), "Error BD", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnVerDetallesVentaActionPerformed

    private void btnActualizarIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarIngresosActionPerformed
            // TODO add your handling code here:
            cargarHistorialVentas();
    
    // Limpiar la tabla de abajo al actualizar
    DefaultTableModel modeloDetalle = (DefaultTableModel) tableProductosVendidos.getModel();
    modeloDetalle.setRowCount(0);
    
    JOptionPane.showMessageDialog(this, "Historial de ventas actualizado correctamente.");
    
    }//GEN-LAST:event_btnActualizarIngresosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarIngresos;
    private javax.swing.JButton btnVerDetallesVenta;
    private javax.swing.JComboBox<String> cboHistorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableHistorialVentas;
    private javax.swing.JTable tableProductosVendidos;
    private javax.swing.JPanel txtIngresosVentas;
    // End of variables declaration//GEN-END:variables
}
