/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas_Tienda;

/**
 *
 * @author Usuario
 */
public class ProveedorBuscarPorRuc extends javax.swing.JPanel {

    /**
     * Creates new form BuscarPorRucProveedor
     */
    public ProveedorBuscarPorRuc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 700));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        jLabel1.setText("BUSCAR PROVEEDOR ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 20, 386, 44);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("RUC:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 110, 50, 16);

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);
        jPanel1.add(btnBuscar);
        btnBuscar.setBounds(550, 90, 103, 46);

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel3.setText("Resultados de la busqueda: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 160, 250, 23);
        jPanel1.add(txtRuc);
        txtRuc.setBounds(120, 90, 393, 46);

        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblResultado);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 200, 670, 320);

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(this::btnSalirActionPerformed);
        jPanel1.add(btnSalir);
        btnSalir.setBounds(280, 570, 200, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // Obtener el RUC escrito
        String rucBuscado = txtRuc.getText().trim();

        // 1. Validar que no esté vacío
        if (rucBuscado.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Ingrese un RUC.",
                "RUC requerido",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );

            txtRuc.requestFocus();
            return;
        }

        // 2. Validar que tenga exactamente 11 dígitos
        if (!rucBuscado.matches("\\d{11}")) {

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "El RUC debe contener exactamente 11 dígitos.",
                "RUC inválido",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );

            txtRuc.requestFocus();
            return;
        }

        // 3. Obtener el modelo de la tabla de resultados
        javax.swing.table.DefaultTableModel modelo
        = (javax.swing.table.DefaultTableModel) tblResultado.getModel();

        // Limpiar resultados anteriores
        modelo.setRowCount(0);

        // 4. Buscar el RUC en los proveedores
        boolean encontrado = false;
        /*
        for (int i = 0; i < Proveedores.modelo.getRowCount(); i++) {

            String ruc = Proveedores.modelo.getValueAt(i, 1).toString();

            if (ruc.equals(rucBuscado)) {

                modelo.addRow(new Object[]{
                    Proveedores.modelo.getValueAt(i, 0),
                    Proveedores.modelo.getValueAt(i, 1),
                    Proveedores.modelo.getValueAt(i, 2),
                    Proveedores.modelo.getValueAt(i, 3),
                    Proveedores.modelo.getValueAt(i, 4),
                    Proveedores.modelo.getValueAt(i, 5)
                });

                encontrado = true;
                break;
            }
        }

        // 5. Si no se encontró
        if (!encontrado) {

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se encontró ningún proveedor con ese RUC.",
                "Proveedor no encontrado",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
        }*/
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        /*this.dispose();

        Proveedores ventana = new Proveedores();
        ventana.setVisible(true);*/
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResultado;
    private javax.swing.JTextField txtRuc;
    // End of variables declaration//GEN-END:variables
}
