/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas_Tienda;

/**
 *
 * @author Usuario
 */
public class ProveedorAgregar extends javax.swing.JPanel {

    /**
     * Creates new form ProveedorAgregar
     */
    public ProveedorAgregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtRuc = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("RUC:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 104, 59, 41));

        jLabel2.setText("NOMBRE:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 162, 71, 39));

        jLabel3.setText("TELEFONO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 213, 71, 38));

        jLabel4.setText("DIRECCION:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 276, -1, -1));

        jLabel6.setText("EMAIL:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 336, -1, -1));

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        jLabel7.setText("AGREGAR PROVEEDOR ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 19, -1, -1));

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 510, 174, 54));

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 510, 174, 54));
        jPanel1.add(txtRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 109, 408, 31));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 162, 408, 31));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 213, 408, 31));
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 269, 408, 31));

        txtEmail.addActionListener(this::txtEmailActionPerformed);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 329, 408, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String ruc = txtRuc.getText().trim();
        String nombre = txtNombre.getText().trim();
        String telefono = txtTelefono.getText().trim();
        String direccion = txtDireccion.getText().trim();
        String email = txtEmail.getText().trim();

        // 1. Verificar campos vacíos
        if (ruc.isEmpty() || nombre.isEmpty() || telefono.isEmpty()
            || direccion.isEmpty() || email.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Complete todos los campos.",
                "Campos incompletos",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        // 2. Validar RUC: exactamente 11 números
        if (!ruc.matches("\\d{11}")) {

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "El RUC debe contener exactamente 11 dígitos.",
                "RUC inválido",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );

            txtRuc.requestFocus();
            return;
        }

        // 3. Validar nombre: solo letras y espacios
        if (!nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ&. ]+")) {

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "El nombre solo debe contener letras.",
                "Nombre inválido",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );

            txtNombre.requestFocus();
            return;
        }

        // 4. Validar teléfono: exactamente 9 números
        if (!telefono.matches("\\d{9}")) {

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "El teléfono debe contener exactamente 9 dígitos.",
                "Teléfono inválido",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );

            txtTelefono.requestFocus();
            return;
        }

        // 5. Validar dirección
        if (direccion.length() < 5) {

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Ingrese una dirección válida.",
                "Dirección inválida",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );

            txtDireccion.requestFocus();
            return;
        }

        // 6. Validar email
        if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Ingrese un correo electrónico válido.\nEjemplo: ventas@empresa.com",
                "Email inválido",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );

            txtEmail.requestFocus();
            return;
        }

        // 7. Verificar si el RUC ya existe
        for (String[] proveedor : Proveedores.proveedores) {

            if (proveedor[1].equals(ruc)) {

                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ya existe un proveedor con ese RUC.",
                    "RUC duplicado",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                );

                txtRuc.requestFocus();
                return;
            }
        }

        // 8. Generar ID automáticamente
        String id = String.format(
            "PR%04d",
            Proveedores.siguienteId
        );

        Proveedores.siguienteId++;

        // 9. Agregar el nuevo proveedor a la tabla
        if (Proveedores.modelo == null) {
            Proveedores.modelo = new javax.swing.table.DefaultTableModel(
                new String[]{"ID", "RUC", "NOMBRE", "TELÉFONO", "DIRECCIÓN", "EMAIL"}, 0
            );
        }

        // Agregar el nuevo proveedor a la tabla
        Proveedores.modelo.addRow(
            new Object[]{
                id,
                ruc,
                nombre,
                telefono,
                direccion,
                email
            }
        );

        // 10. Mensaje de éxito
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Proveedor agregado correctamente.",
            "Registro exitoso",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        // 11. Cerrar esta ventana
        this.dispose();

        // 12. Regresar a Proveedores
        Proveedores ventana = new Proveedores();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
